// Code generated by scripts/gen_go_css.py from aqv/html.py and experiments/report.py; do not edit.

package aqv

const siteCSS = `
:root {
  --bg: #f6f7f6; --surface: #ffffff; --fg: #1b2226; --muted: #5a666b; --line: #dde2e1;
  --accent: #1d5c63; --code-bg: #eef1f0;
  --ok-fg: #1f6b4a; --ok-bg: #e1f1e8; --warn-fg: #8a5a00; --warn-bg: #fbefd6;
  --bad-fg: #a5332a; --bad-bg: #fbe3e0; --muted-fg: #5a666b; --muted-bg: #eceeed;
  --font-display: "Schibsted Grotesk", "Helvetica Neue", Arial, sans-serif;
  --font-body: "Source Sans 3", "Segoe UI", Roboto, Arial, sans-serif;
  --font-mono: "JetBrains Mono", ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  --font-serif: "Source Serif 4", Georgia, "Times New Roman", serif;
  color-scheme: light;
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    --bg: #101517; --surface: #171f22; --fg: #e3e9ea; --muted: #99a6aa; --line: #2a3437;
    --accent: #7cc4c9; --code-bg: #1f292c;
    --ok-fg: #8fd9b2; --ok-bg: #183528; --warn-fg: #f0c46a; --warn-bg: #3a2d12;
    --bad-fg: #f3a198; --bad-bg: #41201d; --muted-fg: #99a6aa; --muted-bg: #222b2e;
    color-scheme: dark;
  }
}
:root[data-theme="dark"] {
  --bg: #101517; --surface: #171f22; --fg: #e3e9ea; --muted: #99a6aa; --line: #2a3437;
  --accent: #7cc4c9; --code-bg: #1f292c;
  --ok-fg: #8fd9b2; --ok-bg: #183528; --warn-fg: #f0c46a; --warn-bg: #3a2d12;
  --bad-fg: #f3a198; --bad-bg: #41201d; --muted-fg: #99a6aa; --muted-bg: #222b2e;
  color-scheme: dark;
}
* { box-sizing: border-box; }
html, body { margin: 0; }
body { background: var(--bg); color: var(--fg); font-family: var(--font-body); font-size: 16px; line-height: 1.55; }
.page { max-width: 1160px; margin: 0 auto; padding-inline: 20px; padding-block: 36px 64px; display: grid; gap: 44px; }
section { display: grid; gap: 16px; min-width: 0; }
h1, h2, h3 { font-family: var(--font-display); margin: 0; line-height: 1.15; text-wrap: balance; }
h1 { font-size: clamp(28px, 5vw, 40px); }
h2 { font-size: 24px; }
h3 { font-size: 17px; }
p { margin: 0; }
a { color: var(--accent); }
code { font-family: var(--font-mono); font-size: 0.85em; background: var(--code-bg); padding: 0.08em 0.35em; border-radius: 4px; overflow-wrap: anywhere; }
.eyebrow { font-family: var(--font-mono); font-size: 12px; letter-spacing: 0.08em; text-transform: uppercase; color: var(--muted); }
.lede { font-size: 19px; max-width: 70ch; }
.muted { color: var(--muted); }
.small { font-size: 14px; }
header.top { display: grid; gap: 12px; }
.stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 12px; }
.stat { background: var(--surface); border: 1px solid var(--line); border-radius: 10px; padding: 16px 18px; display: grid; gap: 4px; min-width: 0; }
.stat b { font-family: var(--font-display); font-size: 28px; font-variant-numeric: tabular-nums; }
.stat span { font-size: 14px; color: var(--muted); }
.chip { display: inline-flex; align-items: center; height: 22px; padding: 0 8px; border-radius: 5px; font-family: var(--font-mono); font-size: 12px; font-weight: 600; white-space: nowrap; }
.chip.ok { color: var(--ok-fg); background: var(--ok-bg); }
.chip.warn { color: var(--warn-fg); background: var(--warn-bg); }
.chip.bad { color: var(--bad-fg); background: var(--bad-bg); }
.chip.muted { color: var(--muted-fg); background: var(--muted-bg); }
.chip.id { color: var(--fg); background: var(--code-bg); }
.chips { display: flex; flex-wrap: wrap; gap: 4px; }
.table-wrap { overflow-x: auto; border: 1px solid var(--line); border-radius: 10px; background: var(--surface); }
table { width: 100%; border-collapse: collapse; font-size: 14.5px; }
th, td { text-align: left; vertical-align: top; padding: 10px 12px; border-bottom: 1px solid var(--line); }
thead th { font-family: var(--font-mono); font-size: 11px; font-weight: 600; letter-spacing: 0.07em; text-transform: uppercase; color: var(--muted); background: var(--bg); }
tbody tr:last-child td { border-bottom: 0; }
tr.group td { font-family: var(--font-display); font-weight: 700; color: var(--accent); background: var(--bg); padding-block: 8px; }
td.id { font-family: var(--font-mono); font-weight: 600; white-space: nowrap; }
td.name { font-weight: 600; }
.matrix th, .matrix td { padding: 6px 4px; text-align: center; border-bottom: 1px solid var(--line); }
.matrix th.check { font-family: var(--font-mono); font-size: 11px; color: var(--muted); writing-mode: vertical-rl; transform: rotate(180deg); height: 44px; padding: 6px 2px; }
.matrix th.scn, .matrix td.scn { text-align: left; position: sticky; left: 0; background: var(--surface); white-space: nowrap; padding-inline: 12px; font-family: var(--font-mono); font-size: 12.5px; z-index: 1; }
.matrix thead th.scn { background: var(--bg); }
.matrix td.gap, .matrix th.gap { border-left: 2px solid var(--line); }
.cell { display: inline-block; width: 16px; height: 16px; border-radius: 4px; vertical-align: middle; }
.cell.hit { background: var(--bad-fg); }
.cell.good { background: var(--ok-fg); }
.cell.also { border: 2px solid var(--bad-fg); }
.cell.pass { width: 6px; height: 6px; border-radius: 50%; background: var(--ok-fg); opacity: 0.55; }
.cell.skip { width: 6px; height: 6px; border-radius: 50%; background: var(--muted); opacity: 0.4; }
.legend { display: flex; flex-wrap: wrap; gap: 16px; font-size: 14px; color: var(--muted); align-items: center; }
.legend span { display: inline-flex; gap: 6px; align-items: center; }
details.scenario { background: var(--surface); border: 1px solid var(--line); border-radius: 10px; }
details.scenario > summary { cursor: pointer; padding: 12px 16px; display: flex; flex-wrap: wrap; gap: 8px 12px; align-items: center; list-style: none; }
details.scenario > summary::-webkit-details-marker { display: none; }
details.scenario > summary .nm { font-family: var(--font-mono); font-weight: 600; font-size: 14px; }
details.scenario > summary .tt { flex: 1 1 280px; min-width: 0; }
details.scenario[open] > summary { border-bottom: 1px solid var(--line); }
details.scenario .inner { padding: 14px 16px 16px; display: grid; gap: 12px; }
summary:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; border-radius: 10px; }
ul.findings { margin: 0; padding-left: 0; list-style: none; display: grid; gap: 6px; font-size: 14.5px; }
ul.findings li { display: grid; grid-template-columns: 44px 1fr; gap: 8px; }
ul.findings li .ck { font-family: var(--font-mono); font-weight: 600; color: var(--bad-fg); }
.reqs { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 10px; }
.req { background: var(--surface); border: 1px solid var(--line); border-radius: 10px; padding: 14px; display: grid; gap: 6px; align-content: start; min-width: 0; }
.req .top { display: flex; justify-content: space-between; gap: 8px; align-items: center; }
.req .id { font-family: var(--font-mono); font-weight: 600; font-size: 13px; }
.req p { font-size: 14.5px; }
.req .why { font-size: 13px; color: var(--muted); }
.req.ok { border-top: 3px solid var(--ok-fg); } .req.warn { border-top: 3px solid var(--warn-fg); }
.req.bad { border-top: 3px solid var(--bad-fg); } .req.muted { border-top: 3px solid var(--muted); }
.goal-list { display: grid; gap: 4px; }
.goal-list .row { display: grid; grid-template-columns: 40px 100px 1fr; gap: 10px; padding: 8px 12px; border-bottom: 1px solid var(--line); align-items: start; }
.goal-list .row:last-child { border-bottom: 0; }
.goal-list .row .ck { font-family: var(--font-mono); font-weight: 600; }
.goal-list .msg { display: block; font-size: 13.5px; color: var(--muted); margin-top: 2px; overflow-wrap: anywhere; }
.panel { background: var(--surface); border: 1px solid var(--line); border-radius: 10px; }
.panel h3 { padding: 12px 12px 4px; }
footer { font-size: 14px; color: var(--muted); border-top: 1px solid var(--line); padding-top: 16px; }
@media (max-width: 640px) { .goal-list .row { grid-template-columns: 36px 1fr; } .goal-list .row > :nth-child(3) { grid-column: 1 / -1; } }
.site-nav { position: sticky; top: 0; z-index: 20; background: var(--bg); border-bottom: 1px solid var(--line); }
.site-nav .in { max-width: 1160px; margin: 0 auto; padding: 10px 20px; display: flex; flex-wrap: wrap; gap: 4px 18px; align-items: baseline; }
.site-nav .brand { font-family: var(--font-display); font-weight: 700; font-size: 15px; color: var(--fg); text-decoration: none; margin-right: auto; }
.site-nav a.lk { color: var(--muted); text-decoration: none; font-size: 14px; }
.site-nav a.lk:hover { color: var(--accent); text-decoration: underline; }
.site-nav a.lk[aria-current="page"] { color: var(--accent); font-weight: 600; }
@media (max-width: 640px) { .site-nav { position: static; } }
`

const viewCSS = `
.sheet { background: var(--surface); border: 1px solid var(--line); border-radius: 10px; }
.clause { display: grid; grid-template-columns: 28px 1fr; border-bottom: 1px solid var(--line); }
.clause:last-child { border-bottom: 0; }
.rail { display: flex; flex-direction: column; gap: 3px; padding: 18px 0 18px 12px; }
.rail span { flex: 1; width: 6px; border-radius: 3px; min-height: 10px; }
.v-ok { background: var(--ok-fg); } .v-warn { background: var(--warn-fg); }
.v-bad { background: var(--bad-fg); } .v-none { background: var(--muted-bg); }
.clause details > summary { list-style: none; cursor: pointer; padding: 14px 20px 14px 10px; }
.clause details > summary::-webkit-details-marker { display: none; }
.clause details[open] > summary { padding-bottom: 4px; }
.clause .head { display: flex; justify-content: space-between; align-items: center; gap: 12px; flex-wrap: wrap; }
.clause .rid { font-family: var(--font-mono); font-size: 13px; color: var(--muted); }
.vitals { display: flex; gap: 10px; font-size: 12px; color: var(--muted); flex-wrap: wrap; }
.vitals span { display: inline-flex; align-items: center; gap: 5px; }
.vitals i { width: 7px; height: 7px; border-radius: 50%; display: inline-block; }
.clause .text { font: 19px/1.5 var(--font-serif); margin: 6px 0 0; }
.clause .text mark { background: none; color: inherit; text-decoration: underline wavy var(--warn-fg);
  text-decoration-thickness: 2px; text-underline-offset: 4px; }
.clause .inner { padding: 0 20px 14px 10px; }
.clause .note { font-size: 14px; margin: 8px 0 8px; }
.note.ok { color: var(--ok-fg); } .note.warn { color: var(--warn-fg); } .note.bad { color: var(--bad-fg); }
.tl { list-style: none; margin: 0; padding: 0 0 4px 3px; border-left: 1px solid var(--line); }
.tl li { position: relative; padding: 4px 0 4px 18px; font-size: 14px; color: var(--muted); overflow-wrap: anywhere; }
.tl li::before { content: ""; position: absolute; left: -5px; top: 12px; width: 9px; height: 9px; border-radius: 50%;
  background: var(--dot, var(--muted-bg)); }
.tl li.now-sep { padding: 8px 0 2px 18px; font-family: var(--font-mono); font-size: 11px; letter-spacing: .07em;
  text-transform: uppercase; }
.tl li.now-sep::before { display: none; }
.tl code { font-family: var(--font-mono); font-size: 12px; margin-right: 8px; color: var(--fg); background: none; padding: 0; }
.orow { display: flex; align-items: baseline; gap: 10px; padding: 11px 18px; border-bottom: 1px solid var(--line);
  font-size: 15px; flex-wrap: wrap; }
.orow:last-child { border-bottom: 0; }
.orow .dot { width: 8px; height: 8px; border-radius: 50%; flex: none; align-self: center; }
.orow code { font-family: var(--font-mono); font-size: 13px; background: none; padding: 0; }
.orow span.msg { color: var(--muted); }
.vlegend { display: flex; gap: 18px; flex-wrap: wrap; font-size: 13px; color: var(--muted); }
.vlegend span { display: inline-flex; align-items: center; gap: 6px; }
.vlegend i { width: 6px; height: 14px; border-radius: 3px; display: inline-block; }
details.all > summary { cursor: pointer; font-family: var(--font-display); font-size: 20px; font-weight: 700; }
`

const fontsHTML = `<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Schibsted+Grotesk:wght@500;700&family=Source+Sans+3:wght@400;600&family=JetBrains+Mono:wght@400;600&family=Source+Serif+4:opsz,wght@8..60,400;8..60,500&display=swap">`

const homeCSS = `
.goal { background: var(--surface); border: 1px solid var(--line); border-left: 4px solid var(--accent);
  border-radius: 10px; padding: 18px 20px; display: grid; gap: 12px; }
.goal .big { font-family: var(--font-display); font-size: 21px; font-weight: 700; line-height: 1.25; }
.fams { display: grid; grid-template-columns: repeat(auto-fit, minmax(230px, 1fr)); gap: 10px; }
.fam { background: var(--surface); border: 1px solid var(--line); border-radius: 10px; padding: 14px 16px;
  display: grid; gap: 6px; align-content: start; min-width: 0; }
.fam .k { font-family: var(--font-mono); font-size: 12px; font-weight: 600; color: var(--accent); }
.fam h3 { font-size: 16px; }
.fam p { font-size: 14.5px; color: var(--muted); }
ul.plain { margin: 0; padding-left: 18px; display: grid; gap: 6px; }
.cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 12px; }
a.card { background: var(--surface); border: 1px solid var(--line); border-radius: 10px; padding: 16px 18px;
  display: grid; gap: 6px; align-content: start; text-decoration: none; color: var(--fg); min-width: 0; }
a.card:hover { border-color: var(--accent); }
a.card:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; }
a.card .k { font-family: var(--font-mono); font-size: 11px; letter-spacing: .07em; text-transform: uppercase; color: var(--muted); }
a.card b { font-family: var(--font-display); font-size: 18px; color: var(--accent); }
a.card span.d { font-size: 14.5px; color: var(--muted); }
.dir { display: grid; gap: 10px; }
.dir .grp { background: var(--surface); border: 1px solid var(--line); border-radius: 10px; }
.dir .grp > h3 { padding: 12px 16px; border-bottom: 1px solid var(--line); }
.dir ul { list-style: none; margin: 0; padding: 4px 0; }
.dir li { display: flex; flex-wrap: wrap; gap: 4px 12px; align-items: baseline; padding: 8px 16px; border-bottom: 1px solid var(--line); }
.dir li:last-child { border-bottom: 0; }
.dir li .t { font-weight: 600; min-width: 0; }
.dir li .d { color: var(--muted); font-size: 14px; flex: 1 1 260px; }
.dir li .alt { font-family: var(--font-mono); font-size: 12px; }
.dir details { border-top: 1px solid var(--line); }
.dir details > summary { cursor: pointer; padding: 10px 16px; font-size: 14px; color: var(--accent); }
.dir details ul { columns: 2 260px; column-gap: 0; padding-bottom: 8px; }
.dir details li { break-inside: avoid; border-bottom: 0; padding: 3px 16px; font-size: 13.5px; }
.dir details li code { background: none; padding: 0; }
`

const compareCSS = `
.goal { background: var(--surface); border: 1px solid var(--line); border-left: 4px solid var(--accent);
  border-radius: 10px; padding: 18px 20px; display: grid; gap: 12px; }
.goal .big { font-family: var(--font-display); font-size: 21px; font-weight: 700; line-height: 1.25; }
.fams { display: grid; grid-template-columns: repeat(auto-fit, minmax(230px, 1fr)); gap: 10px; }
.fam { background: var(--surface); border: 1px solid var(--line); border-radius: 10px; padding: 14px 16px;
  display: grid; gap: 6px; align-content: start; min-width: 0; }
.fam .k { font-family: var(--font-mono); font-size: 12px; font-weight: 600; color: var(--accent); }
.fam h3 { font-size: 16px; }
.fam p { font-size: 14.5px; color: var(--muted); }
ul.plain { margin: 0; padding-left: 18px; display: grid; gap: 6px; }
.cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 12px; }
a.card { background: var(--surface); border: 1px solid var(--line); border-radius: 10px; padding: 16px 18px;
  display: grid; gap: 6px; align-content: start; text-decoration: none; color: var(--fg); min-width: 0; }
a.card:hover { border-color: var(--accent); }
a.card:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; }
a.card .k { font-family: var(--font-mono); font-size: 11px; letter-spacing: .07em; text-transform: uppercase; color: var(--muted); }
a.card b { font-family: var(--font-display); font-size: 18px; color: var(--accent); }
a.card span.d { font-size: 14.5px; color: var(--muted); }
.dir { display: grid; gap: 10px; }
.dir .grp { background: var(--surface); border: 1px solid var(--line); border-radius: 10px; }
.dir .grp > h3 { padding: 12px 16px; border-bottom: 1px solid var(--line); }
.dir ul { list-style: none; margin: 0; padding: 4px 0; }
.dir li { display: flex; flex-wrap: wrap; gap: 4px 12px; align-items: baseline; padding: 8px 16px; border-bottom: 1px solid var(--line); }
.dir li:last-child { border-bottom: 0; }
.dir li .t { font-weight: 600; min-width: 0; }
.dir li .d { color: var(--muted); font-size: 14px; flex: 1 1 260px; }
.dir li .alt { font-family: var(--font-mono); font-size: 12px; }
.dir details { border-top: 1px solid var(--line); }
.dir details > summary { cursor: pointer; padding: 10px 16px; font-size: 14px; color: var(--accent); }
.dir details ul { columns: 2 260px; column-gap: 0; padding-bottom: 8px; }
.dir details li { break-inside: avoid; border-bottom: 0; padding: 3px 16px; font-size: 13.5px; }
.dir details li code { background: none; padding: 0; }

.quote { background: var(--surface); border: 1px solid var(--line); border-left: 4px solid var(--muted);
  border-radius: 10px; padding: 16px 20px; display: grid; gap: 8px; }
.quote blockquote { margin: 0; font-family: var(--font-serif); font-size: 18px; line-height: 1.5; }
.quote .src { font-size: 13px; color: var(--muted); }
.two { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 12px; }
.two .panel { padding: 16px 18px; display: grid; gap: 8px; align-content: start; }
.two .panel h3 { padding: 0; }
.two .panel .k { font-family: var(--font-mono); font-size: 11px; letter-spacing: .07em; text-transform: uppercase; color: var(--muted); }
.two .panel.ours { border-top: 3px solid var(--accent); }
.two .panel.theirs { border-top: 3px solid var(--muted); }
td.why { color: var(--muted); font-size: 14px; min-width: 240px; }
td.scn { font-family: var(--font-mono); font-size: 12.5px; white-space: nowrap; }
td .ttl { display: block; font-family: var(--font-body); font-size: 13.5px; color: var(--muted); white-space: normal; max-width: 300px; }
.note { font-size: 14px; color: var(--muted); }
ol.steps { margin: 0; padding-left: 20px; display: grid; gap: 8px; }
.vs { --ours: var(--accent); --ours-fg: var(--accent); --subj: #8a96a3; --subj-fg: #56626e;
  background: color-mix(in srgb, var(--accent) 5%, var(--surface));
  border: 1px solid color-mix(in srgb, var(--accent) 35%, var(--line)); border-radius: 14px;
  padding: 22px 24px 18px; display: grid; gap: 4px; }
@media (prefers-color-scheme: dark) { :root:not([data-theme="light"]) .vs { --subj: #6b7783; --subj-fg: #aeb8c2; } }
:root[data-theme="dark"] .vs { --subj: #6b7783; --subj-fg: #aeb8c2; }
.vs-legend { display: flex; flex-wrap: wrap; gap: 6px 20px; font-size: 13.5px; color: var(--muted); padding-bottom: 12px; }
.vs-legend span { display: inline-flex; align-items: center; gap: 7px; }
.sw { display: inline-block; width: 22px; height: 10px; border-radius: 99px; }
.sw.ours { background: var(--ours); }
.sw.auto { background: var(--subj); }
.sw.review { background: repeating-linear-gradient(135deg, var(--subj) 0 3px, transparent 3px 6px); border: 1px solid var(--subj); }
.sw.none { border: 1px dashed var(--subj); }
.vs-row { display: grid; grid-template-columns: minmax(0, 1.5fr) minmax(0, 1fr) minmax(0, 1fr); gap: 10px 28px;
  align-items: center; padding: 14px 0; border-top: 1px solid var(--line); }
.vs-row.head { border-top: 0; padding: 0 0 8px; font-family: var(--font-mono); font-size: 11px; letter-spacing: .07em;
  text-transform: uppercase; color: var(--muted); }
.vs-row.head .o { color: var(--ours-fg); font-weight: 600; } .vs-row.head .s { color: var(--subj-fg); font-weight: 600; }
.vs-q { font-size: 16px; font-weight: 600; line-height: 1.35; }
.vs-q small { display: block; margin-top: 3px; font-family: var(--font-mono); font-size: 11.5px; font-weight: 400; color: var(--muted); }
.vs-cell { display: grid; gap: 6px; min-width: 0; align-content: start; }
.meter { display: flex; height: 12px; border-radius: 99px; background: var(--muted-bg); overflow: hidden; }
.meter i { display: block; height: 100%; }
.meter.ours i { background: var(--ours); }
.meter i.auto { background: var(--subj); }
.meter i.review { background: repeating-linear-gradient(135deg, var(--subj) 0 3px, transparent 3px 6px); }
.meter.none { background: transparent; border: 1px dashed var(--subj); }
.vs-val { font-family: var(--font-mono); font-size: 12.5px; color: var(--muted); display: flex; flex-wrap: wrap; gap: 2px 10px; }
.vs-val b { font-size: 14px; }
.vs-cell.ours .vs-val b { color: var(--ours-fg); }
.vs-cell.subj .vs-val b { color: var(--subj-fg); }
.vs-row.total { align-items: start; border-top: 2px solid color-mix(in srgb, var(--accent) 35%, var(--line)); margin-top: 4px; padding-top: 16px; }
.vs-row.total .meter { height: 18px; }
.vs-row.total .vs-val b { font-size: 18px; font-family: var(--font-display); }
@media (max-width: 720px) {
  .vs { padding: 18px 16px 14px; }
  .vs-row { grid-template-columns: 1fr 1fr; align-items: start; }
  .vs-row .vs-q { grid-column: 1 / -1; }
  .vs-row.head > :first-child { display: none; }
}
.key { background: var(--surface); border: 1px solid var(--line); border-radius: 10px; padding: 14px 18px; display: grid; gap: 8px; }
.key-title { font-family: var(--font-mono); font-size: 11px; letter-spacing: .07em; text-transform: uppercase; color: var(--muted); }
.key-row { display: grid; grid-template-columns: 220px 1fr; gap: 4px 14px; align-items: baseline; font-size: 14.5px; }
.key-row p { color: var(--muted); }
@media (max-width: 640px) { .key-row { grid-template-columns: 1fr; } }
.two.quad { grid-template-columns: repeat(auto-fit, minmax(min(100%, 420px), 1fr)); }
`
