"""Writes internal/aqv/css_gen.go from the Python page modules, so the Go pages use byte-identical CSS.

    .venv/bin/python scripts/gen_go_css.py
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "experiments"))
from aqv import html  # noqa: E402
import report  # noqa: E402


def main():
    out = ["// Code generated by scripts/gen_go_css.py from aqv/html.py and experiments/report.py; do not edit.", "",
           "package aqv", ""]
    for name, val in [("siteCSS", html.CSS), ("viewCSS", html.VIEW_CSS), ("fontsHTML", html.FONTS),
                      ("homeCSS", html.SITE_CSS), ("compareCSS", report.CSS)]:
        assert "`" not in val, name
        out.append(f"const {name} = `{val}`")
        out.append("")
    (ROOT / "internal" / "aqv" / "css_gen.go").write_text("\n".join(out))
    print("wrote internal/aqv/css_gen.go")


if __name__ == "__main__":
    main()
